language: bash
sudo: required
branches:
  only:
    - development
services:
- docker
env:
  global:
  - secure: gRo2pr+yqkwLXjXZUqvZpZkWNaYAdId26PBGYDFYYwsP3w/UUslddFtbQybJNHyhv4EcfBtKegcQqAnQ19XFvYpM6zAGCxHcQVzDVFCmZV4uV7x0PmSfDQfpm40QwZdl7IW4P1Az1ppk8Sa+C62DhLGa4c4N++E9Sbq3K7n1QabSFw1K3XD1XSLOHdZP+OBqM5UJlkPNP5lTq8115EYUGlY+YMI1vnT9HtQN1v/9xKmV/PhnTmZxcT2a6I6ffeUSqHbsyM+qhYLIOrlOH/IHVSkdxTOFWuC5FBBt2XxT5lgba1nnZPNxJGXCwd58eoD1IKEGwHvLXzQlbNUT4hKY1XK8KJQwZBYxkkoB3hiHp4mmdmQfqCjUeKq6OLbJ7CKeNWuTkUcve5z+0BSur088SnpN1h/5ABLOhqAHdGoEo04ooAAb+AEz69XixeOXEXVpHt89XNz48RsWY5SsKR5FKG9G+FrYb7pp6qiIcn3WfmQD/o9P/uhV2e/c0KgH0x1Z5ZS6L/mShqnI+87l5niRcbv4zSGHscYHOvqik0n6K10Fut+z5yJQIGFKp7uSzOrhU/fFo3CDZ8RbyYEhg9kMrnMHXkMTRYJIqSpgw8/kWE8VpgTX9gY+Sq28jLenS6oZot60BnWYHNhWWKhxpBetGFeCAddYevt7V2b4iteqfBY=
  - secure: LjJ3DFFCoCXR9qR9b1NeNpvHJa+Pb46ydJ3IHtbT/Xbsh/DdEKTHukZ5h4zAj7+uVVEPUXHPheqIHGo/qlMqpL2mevhKDTZQQqRM+Xx+wf7Epfm/ivCUJVNdXdDNCOODp+oaMJAPQdqteOVdwiEyVT8RGKjmgyFSp2KD2/ArCnfd91KS6g0rNZaHFfUu89Dx38+S8aY6wpt4TFPJLlxqyxi2NqtUkidqH9ZMuyFOe0SFfA699bMxTjKPIrwPpqUzb4AKZizppuXnZriqpF9vL0+dHmcB5xLQXaik5MKMr4FENbJ5amDgsn98gFOvRQm4zG/HbIv+vpdJy/ClADSyVYICycm6BPk/Bjm91xm7ggRCAvc6RNgfNUmFjChGHe6o6aNPvvBC5e1OqVbZNKZ96dGdrW2fcpmAeD8Khhlc+alEzST09Ijb4VS/CRPJyIJGqAc8N5U1wDaO2ZSQ3vuRiVy3/UmeS0RHbB2ci32c3etzOpLPpZmO0ql7QiqO6wNL73zF7Fj/aCDQ3fwPUF6IHC4jVcdhJcXPdl7STk/kgbXbAyNQ9f1o8GDoJEX3pu9N4p1/WzvdA51pMp+h7CE20S+ILasOanu0CpDK8dnSwgiRHdLj1xh9YJIg/KPeGo0xr+BSYIV8wP3tCd/T/T6eRy2Kionx+0x0yboeTd7IS+4=
  - secure: dFE/aX0vZSiseDhGZS/SOroB0LohtqXgMIUprJiLTUUwXtv2PDBX7HPRaPlInITDHFt6Gx3Qhkl+5bOBbb7QgfespjUrIveP5WCtKGvdVwy3ppiuPpKXtIjgthBJOArHw846+QqLG0FNntkm2cyUZG/BSnJir/xg58c/DhjmUZxXVD45utBubGCKLv7vV57l2NcgOYBQFrolazGpuCu6Vu6cNlKhF6J8/pUJtfDAqtpoSMIzNmTwn0s2J/x9wbL1ShzimB+NToA481tRjh8Ugw+BsTO+pSulr/8ywLUPulw/rh9FL6ua4cCCkhCMaqFLef/Fx+qkHLYvIZ17Ht9CIlIhTNzOP13X7IzyZvia9t0d22SjUnnhq0AKnSbApm8jloRgvgiw8sYSYigzFuRGr3eu/MKrVLNVTqaujsgyRVD8FhPkAIBobNs+f8PxIgJ/3Gj++Bc9ZiRhToOdgcwmWEP5kUakDjyh6BBbyPozF87BpftrrhwOf62IC7txqAtNc572t5YKpajRVromrYrC9gzYse4ajD06LJHJya+0ehilW8FYbddRnB2+eLfgz3Tgzv2LwA1oYRe7uRDDB9Yn9+FZwvDOYb9+/ffnKCrrTDvkC4dEa45Z++y1ZYi4STPi9cJwokpzfGCDxHQgjQKGsgRmvfpU6vNwb9oJArwNcLM=

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker build -t lrsdevelopment/dog-rails-dev .
  - docker run -d -e POSTGRES_USER=test --privileged=true --name=db mdillon/postgis:9.4
  - docker run -e RAILS_ENV=test --name=dog-rails-test --link=db lrsdevelopment/dog-rails-dev rake migrate

script:
  - docker run -e RAILS_ENV=test --name=dog-rails-test --link=db lrsdevelopment/dog-rails-dev rake test

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" tatum.co
  - docker push dog-rails-dev
