# This compose file is used by tutum to build a container and execute rspec tests in that
# container. If tests fail, the image will not be pushed to the registry. A database container
# with postgres and postgis extensions is pulled and initialized to reflect the production
# environment. 
#
#
sut:
  image: this
  environment:
    RAILS_ENV: test
  links:
    - db
  command: /bin/sh run_tests_tutum.sh

db:
  image: mdillon/postgis:9.4
  privileged: true
  environment:
    POSTGRES_USER: test
