# This compose file builds the dog rails app and executes rspec tests.
# DB container is the same Postgres version as the production RDS instance.
dograils-test:
  build: .
  environment:
    - RAILS_ENV=test
  links:
    - db
  command: rake spec

db:
  image: mdillon/postgis:9.4
  environment:
    POSTGRES_USER=test
