# This compose file is used by tutum to build a container and execute rspec tests in that
# container. If tests fail, the image will not be pushed to the registry. A database container
# with postgres and postgis extensions is pulled and initialized to reflect the production
# environment. (Pushes to the development repository are built automatically by tutum)
#
# Equally, this file can be used to test locally on a dev machine with docker and docker-compose
# installed. Execute run_tests.sh on the command line.
#
sut:
  build: .
  environment:
    RAILS_ENV: test
  links:
    - db
  command: rake spec

db:
  image: mdillon/postgis:9.4
  privileged: true
  environment:
    POSTGRES_USER: test
