## AWS credentials supplied by environment variables
development: &default
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %> 

production:
  <<: *default

test:
  <<: *default
